backend/backend/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import (
    PythonSocialAuthComplete,
    PythonSocialAuthLoginError,
    index,
    ApiEndpoint,
)

from django.views.decorators.csrf import csrf_exempt

urlpatterns = [

    # prototype index
    url(r'^$', index, name='index'),

    # Django Admin
    url(r'^admin/', admin.site.urls),

    # emails app
    url(r'', include('emails.urls', namespace='emails')),

    # users app
    url(r'', include('users.urls', namespace='users')),

    # OAuth login error, and successful views
    url(r'^login-error/$', PythonSocialAuthLoginError.as_view()),

    url(r'^complete/(?P<backend>[^/]+)/$', PythonSocialAuthComplete.as_view()),

    # Django REST framework api_v1 auth
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Python social apps URL
    url(r'', include('social.apps.django_app.urls', namespace='social')),

    # Django OAuth Toolkit
    url(r'^oauth/', include('oauth2_provider.urls', namespace='oauth2_provider')),

    url(r'^api/hello', csrf_exempt(ApiEndpoint.as_view())),
]

backend/emails/api/v1/gmail/urls.py
from django.conf.urls import url

from . import api_views

urlpatterns = [
    url(r'^tid-index/?$', api_views.TidIndexView.as_view()),
    url(r'^tid-index/(?P<pk>\d+)', api_views.TidIndexDetailView.as_view()),

    url(r'^mid-index/?$', api_views.MidIndexView.as_view()),
    url(r'^mid-index/(?P<pk>\d+)', api_views.MidIndexDetailView.as_view()),

    url(r'^profiles/?$', api_views.ProfilesView.as_view()),
    url(r'^profiles/(?P<pk>\d+)', api_views.ProfileDetailView.as_view()),

    # /api/v1/gmail/labels: list the email account's labels (a.k.a. mailboxes)
    url(r'^labels/?$', api_views.LabelsView.as_view()),

    url(r'^update-index/(?P<profile_id>\d+)', api_views.UpdateIndexView.as_view()),

    # url(r'^reset-index/(?P<profile_id>\d+)', api_views.ResetIndexView.as_view()),
]

backend/emails/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^api/v1/gmail/', include('emails.api.v1.gmail.urls', namespace='emails-api-v1')),
]

backend/users/api/v1/urls.py
from django.conf.urls import url

from . import api_views

urlpatterns = [
    # list users, or create a new email profile
    url(r'^users/?$', api_views.UsersView.as_view(), name='users'),

    # get a user by pk
    url(r'^users/(?P<pk>\d+)/?$', api_views.UsersDetailView.as_view(), name='users_detail'),
]

backend/users/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout, login_required

from . import views

urlpatterns = [
    url(r'^api/v1/', include('users.api.v1.urls', namespace='users_api_v1')),

    # login
    url(
        r'^users/login',
        login,
        kwargs={
            'template_name': 'users/login.html'
        },
        name='login'
    ),

    # logout
    url(
        r'^users/logout',
        logout,
        kwargs={
            'template_name': 'users/logout.html'
        },
        name='logout'
    ),

    # profile
    url(
        r'^users/profile/?$',
        login_required(views.UserProfile.as_view()),
        name='profile'
    ),
]

backend/backend/models.py
from django.contrib.auth.models import User
from django.db import models
from django_celery_results.models import TaskResult

job_type_choices = (
    ('gmail-update', 'emails.tasks.update_gmail_message_index'),
)


class AsyncTaskResult(models.Model):

    task_id = models.CharField(unique=True, max_length=40)

    user = models.ForeignKey(User)

    created = models.DateTimeField(auto_now_add=True)

    job_type = models.CharField(choices=job_type_choices, max_length=20)

backend/backend/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View

from social.apps.django_app.views import complete
from social.exceptions import AuthFailed, AuthAlreadyAssociated


class PythonSocialAuthComplete(View):
    @staticmethod
    def get(request, *args, **kwargs):
        backend = kwargs.pop('backend')
        try:
            return complete(request, backend, *args, **kwargs)
        except AuthFailed:
            return HttpResponseRedirect(reverse('login'))
        except AuthAlreadyAssociated:
            return HttpResponseRedirect(reverse('login'))


class PythonSocialAuthLoginError(View):
    @staticmethod
    def get(request):
        return HttpResponse(status=401)


def index(request):
    """
    Simple index logic
    :param request:
    :return:
    """
    return render(request, 'index.html', {'user': request.user})


from django.http.response import HttpResponse
from oauth2_provider.views.generic import ProtectedResourceView
class ApiEndpoint(ProtectedResourceView):
    def get(self, request, *args, **kwargs):
        return HttpResponse('Hello, Oauth2!')
    def post(self, request, *args, **kwargs):
        return HttpResponse('Hello, OAuth2, by POST method!!')

backend/users/views.py
from django.shortcuts import render
from django.views.generic import View


class UserProfile(View):
    @staticmethod
    def get(request):
        return render(request, 'users/profile.html', {'user': request.user})

    @staticmethod
    def post(request):
        password = request.POST.get('password')
        if password and request.user.is_authenticated:
            request.user.set_password(password)
            request.user.save()
        return render(request, 'users/profile.html', {'user': request.user})

backend/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LifeMotif Prototype Index</title>
</head>
<body>
    {% if user.is_authenticated %}
        <p>You are currently signed in as {{ user.email }}</p>
        <p>
            Visit
            <a href="{% url 'users:profile' %}">
                profile page
            </a>
        </p>
    {% else %}
        <p>
            Do you want to login via Google OAUTH2?
            <a href="{%  url 'social:begin' backend='google-oauth2' %}">
                Visit here,
            </a>
            or login via <a href="{% url 'users:login' %}">login page</a>.
        </p>
    {% endif %}
    <p>
        <a href="{%  url 'admin:index' %}">Django Admin</a>
    </p>
</body>
</html>

backend/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LifeMotif Prototype Login</title>
</head>
<body>
<h1>
    Login
</h1>

{% if form.errors %}
    <p>Incorrect ID, or password!</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
        <p>
            You're not authorized to access the page. Please login with another account.
        </p>
    {% else %}
        <p>
            You are about to access a page that requires authentication. Please login.
        </p>
    {% endif %}
{% endif %}

{% if user.is_authenticated %}
    <p>
        You are currently signed in as {{ user.email }}
        <a href="{% url 'users:logout' %}">
            Sign Out
        </a>
    </p>
{% else %}
    <p>
        Do you want to login via Google OAUTH2?
        <a href="{% url 'social:begin' backend='google-oauth2' %}">
            Visit here
        </a>
    </p>
{% endif %}
<p>
    <a href="{% url 'admin:index' %}">Django Admin</a>
</p>

<div>
    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        <div>
            <ul>
                {{ form.username.label_tag }}
                {{ form.username }}
            </ul>
            <ul>
                {{ form.password.label_tag }}
                {{ form.password }}
            </ul>
        </div>
        <div>
            <input type="submit" value="Sign In"/>
            <input type="hidden" name="next" value="{{ next }}"/>
        </div>
    </form>
</div>
</body>
</html>

backend/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LifeMotif Prototype Login</title>
</head>
<body>
    <h1>
        Logout
    </h1>
    <p>
        <a href="{% url 'users:login' %}">
            Sign in again
        </a>
    </p>
</body>
</html>

backend/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
</head>
<body>
<h1>Profile</h1>
{% if not request.user.is_authenticated %}
    You are not logged in!
{% else %}
    <div>
        <p>
            <a href="{% url 'index' %}">Home</a> |
            <a href="{% url 'users:logout' %}">
                Logout
            </a>
        </p>
    </div>
    <div>
        <ul>
            <li>
                Email: {{ user.email }}
            </li>
            <li>
                First name: {{ user.first_name }}
            </li>
            <li>
                Last name: {{ user.last_name }}
            </li>
            <li>
                Joined: {{ user.date_joined }}
            </li>
            <li>
                Last login: {{ user.last_login }}
            </li>
            <li>
                Super User:
                {% if user.is_superuser %}
                    Yes
                {% else %}
                    No
                {% endif %}
            </li>
            <li>
                Staff:
                {% if user.is_staff %}
                    Yes
                {% else %}
                    No
                {% endif %}
            </li>

        </ul>
    </div>
    <div>
        <h2>Change password</h2>
        <form method="post" action="{% url 'users:profile' %}">
            <ul>
                <li>
                    <label for="password">Input password</label>
                    <input id="password" type="password" name="password">
                </li>
                <li>
                    <label for="password-confirm">Type again</label>
                    <input id="password-confirm" type="password">
                </li>
            </ul>
            <input type="submit" value="Change Password">
            {% csrf_token %}
        </form>
    </div>
    <script type="text/javascript">
        var password = document.getElementById('password');
        var passwordConfirm = document.getElementById('password-confirm');
        var submit = document.querySelector('form input[type="submit"]');

        function checkIdentical() {
            if (password.value == "" || passwordConfirm.value == "") {
                submit.disabled = true;
                return;
            }
            submit.disabled = (password.value != passwordConfirm.value);
        }

        [password, passwordConfirm].forEach(function(item) {
            item.addEventListener("keyup", checkIdentical);
        });
        checkIdentical();
    </script>
{% endif %}
</body>
</html>